-- NOTE: This file is auto generated by ./sql-generator

-- OCRInfoRepository.searchOcr
select
  "assets".*,
  ts_rank(
    to_tsvector(f_unaccent (ocr_info.text)),
    to_tsquery(f_unaccent ($1))
  ) as "rank"
from
  "assets"
  inner join "exif" on "assets"."id" = "exif"."assetId"
  inner join "ocr_info" on "assets"."id" = "ocr_info"."assetId"
where
  "assets"."fileCreatedAt" >= $2
  and "exif"."lensModel" = $3
  and "assets"."ownerId" = any ($4::uuid[])
  and "assets"."isFavorite" = $5
  and "assets"."isArchived" = $6
  and "assets"."deletedAt" is null
  and to_tsvector(f_unaccent (ocr_info.text)) @@ to_tsquery(f_unaccent ($7))
order by
  "rank"
limit
  $8
offset
  $9
