-- NOTE: This file is auto generated by ./sql-generator

-- OCRInfoRepository.searchOcr
select
  "assets".*
from
  "assets"
  inner join "exif" on "assets"."id" = "exif"."assetId"
  inner join "ocr_info" on "assets"."id" = "ocr_info"."assetsId"
where
  "assets"."fileCreatedAt" >= $1
  and "exif"."lensModel" = $2
  and "assets"."ownerId" = any ($3::uuid[])
  and "assets"."isFavorite" = $4
  and "assets"."isArchived" = $5
  and "assets"."deletedAt" is null
  and f_unaccent (ocr_info.text) ilike '%' || f_unaccent ($6) || '%'
limit
  $7
offset
  $8
